---
  - name: Deploy Script to Remote Servers
    hosts: all
    become: yes
    vars_files:
      - env_vars.yml         
    tasks:
      - name: Ensure required packages are installed
        apt:
          name: "{{ item }}"
          state: present
        loop:
          - git
          - python3
          - python3-pip
          - python3-venv

      - name: Clone repository if not present
        git:
          repo: "https://yahavg10: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@github.com/yahavg10/marsifier.git"
          dest: /home/yahav/marsifier
          version: main
          update: no

      - name: Pull latest changes from main branch
        git:
          repo: "https://yahavg10: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@github.com/yahavg10/marsifier.git"
          dest: /home/yahav/marsifier
          version: main
          update: yes

      - name: Create virtual environment
        command: python3 -m venv /home/yahav/marsifier/myenv
        args:
          creates: /home/yahav/marsifier/myenv/bin/activate

      - name: Start the virtual env
        command: source /home/yahav/marsifier/env/bin/activate

      - name: Install requirements
        pip:
          requirements: /home/yahav/marsifier/deployment/requirements.txt
          executable: pip3

      - name: Copy service file
        copy:
          src: /home/yahav/marsifier/deployment/mars.service
          dest: /etc/systemd/system/deployment/mars.service
          mode: '0755'

      - name: Reload systemd
        command: systemctl daemon-reload

      - name: Enable and start the service
        systemd:
          name: mars
          state: started
          enabled: yes
