---
  - name: Deploy Script to Remote Servers
    hosts: all
    become: yes
    vars_files:
      - env_vars.yml

    environment:
      APP_CONFIG_PATH: configurations/app.yml
      ENV: production
      LOG_CONFIG_PATH: configurations/logger.yml

    tasks:
      - name: Ensure required packages are installed
        apt:
          name: "{{ item }}"
          state: present
        loop:
          - git
          - python3
          - python3-pip
          - python3-venv

      - name: Clone repository if not present
        git:
          repo: "https://yahavg10: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@github.com/yahavg10/marsifier.git"
          dest: "{{ project_folder }}"
          version: main
          update: no

      - name: Pull latest changes from main branch
        git:
          repo: "https://yahavg10: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@github.com/yahavg10/marsifier.git"
          dest: "{{ project_folder }}"
          version: main
          update: yes
          force: true

      - name: Create virtual environment
        command: python3 -m venv {{ venv_folder }}
        args:
          creates: "{{ venv_folder }}/bin/activate"

      - name: Install project requirements in venv
        pip:
          requirements: '{{ requirements_file }}'
          virtualenv: '{{ venv_folder }}'
          virtualenv_python: python3

      - name: Copy service file
        copy:
          src: "{{ service_file }}"
          dest: "{{ service_file }}"
          remote_src: yes
          mode: '0755'

      - name: Reload systemd
        command: systemctl daemon-reload

      - name: Enable and start the service
        systemd:
          name: mars
          state: started
          enabled: yes
