components:
  database:
    host: '20.54.253.55'
    port: 6379
    db: 0

  sender:
    api_url: "http://4.180.218.18:8000/merge-files/"

  pipeline_executor:
    folder_path: "/home/yahav/images"
    expiry_delay: 60
    max_workers: 500
    handling_way: "multithread"