receivers:
  file:
    path:
      model_name: "FileDataSourceHandler"
      model_path: "src.receiver.data_sources_handlers.file_handler"
    conf:
      folder_to_monitor: "/home/yahav/images"
      file_age_limit: 1 # in minutes

databases:
  directory: "src/database/databases_handlers"
  types:
    redis:
      host: '20.54.253.55'
      port: 6379
      db: 0
      expiry: 60


sender:
  file_invoker:
    endpoint: "http://4.210.254.55:7180/merge-files/"
    params:
      folder_path: "/home/yahav/images"
      suffixes: [ "_a.jpg", "_b" ]

pipeline:
  folder_path: "/home/yahav/images"
  config_module: "configurations.developer_config"
  steps_module: "src.pipeline_runner.pipeline_utils"
